services:
  app:
    image: parksofprague:latest
    build:
      context: .
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    command:
      ["--hostname", "0.0.0.0", "--port", "8080", "--environment", "production"]
    profiles: ["prod"]
  db:
    image: postgres:16-alpine3.20
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles: ["prod"]
  db-dev:
    image: postgres:16-alpine3.20
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata-dev
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    profiles: ["dev"]
  db-test:
    image: postgres:16-alpine3.20
    env_file:
      - .env_test
    ports:
      - "${POSTGRES_PORT}:5432"
    profiles: ["test"]
volumes:
  db_data:
